env: "local"

db:
  host: 172.17.0.2
  port: 5432
  user: product
  database: product_service_db
  ssl_mode: disable
http:
  port: "8080"
  handler: router
  read_timeout: 10s
  write_timeout: 30s
  idle_timeout: 120s